# Generated by Django 4.0.3 on 2022-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('specie', models.CharField(max_length=100)),
                ('date_discovered', models.DateField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('lifespan', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('locations', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
