# Generated by Django 4.0.4 on 2022-05-07 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sealife', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='specie',
            new_name='species',
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='sealife.categories'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_discovered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
