# Generated by Django 4.0.4 on 2022-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealife', '0002_rename_specie_animal_species_alter_animal_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(),
        ),
    ]
